/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vista;

/**
 *
 * @author CRISTIAN
 */
public class FormVentas extends javax.swing.JFrame {

    /**
     * Creates new form FormVentas
     */
    public FormVentas() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jpanelProductos = new javax.swing.JPanel();
        nameWelcome = new javax.swing.JLabel();
        separadorMin = new javax.swing.JLabel();
        jtxtNomCliente = new javax.swing.JTextField();
        jButtonRegresar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jtxtDniORuc = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jcbxTipoDoc = new javax.swing.JComboBox<>();
        jTextFieldCodProc = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jTextFieldPrecioUnitario = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jButtonAgregar = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jtxtValorVenta = new javax.swing.JTextField();
        jtxtDescuento = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jtxtSubtotal = new javax.swing.JTextField();
        jtxtIGV = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jtxtTotalPagar = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jButtonImprimir = new javax.swing.JButton();
        jButtonGenerarVenta = new javax.swing.JButton();
        jspnCantidadProducto = new javax.swing.JSpinner();
        jTextFieldStock = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTableVenta = new javax.swing.JTable();
        btnReporteVentas = new javax.swing.JButton();
        jButtonCancelarVenta = new javax.swing.JButton();
        jButtonBuscarProd = new javax.swing.JButton();
        jButtonBuscarCliente = new javax.swing.JButton();
        jtxtNombre = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        FondoMenu = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jpanelProductos.setBackground(new java.awt.Color(255, 255, 255));
        jpanelProductos.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        nameWelcome.setFont(new java.awt.Font("Rubik", 1, 28)); // NOI18N
        nameWelcome.setText("Sistema Gestión Pesquera");
        jpanelProductos.add(nameWelcome, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 40, 430, 30));

        separadorMin.setFont(new java.awt.Font("Rubik", 1, 28)); // NOI18N
        separadorMin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/separador-min.png"))); // NOI18N
        jpanelProductos.add(separadorMin, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 80, -1, 10));

        jtxtNomCliente.setFont(new java.awt.Font("Rubik", 0, 16)); // NOI18N
        jtxtNomCliente.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(179, 179, 179)));
        jpanelProductos.add(jtxtNomCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 140, 320, 40));

        jButtonRegresar.setBackground(new java.awt.Color(238, 238, 238));
        jButtonRegresar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/btn-regresar.png"))); // NOI18N
        jButtonRegresar.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 0, true));
        jButtonRegresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRegresarActionPerformed(evt);
            }
        });
        jpanelProductos.add(jButtonRegresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 460, 200, 56));

        jLabel1.setFont(new java.awt.Font("Rubik Medium", 0, 14)); // NOI18N
        jLabel1.setText("Nombre de cliente");
        jpanelProductos.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 120, -1, -1));

        jLabel2.setFont(new java.awt.Font("Rubik Medium", 0, 14)); // NOI18N
        jLabel2.setText("DNI ó RUC");
        jpanelProductos.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 120, -1, -1));

        jtxtDniORuc.setFont(new java.awt.Font("Rubik", 0, 16)); // NOI18N
        jtxtDniORuc.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(179, 179, 179)));
        jpanelProductos.add(jtxtDniORuc, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 140, 150, 40));

        jLabel3.setFont(new java.awt.Font("Rubik Medium", 0, 14)); // NOI18N
        jLabel3.setText("Tipo de documento");
        jpanelProductos.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 120, -1, -1));

        jcbxTipoDoc.setFont(new java.awt.Font("Rubik", 0, 16)); // NOI18N
        jcbxTipoDoc.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "BOLETA", "FACTURA" }));
        jpanelProductos.add(jcbxTipoDoc, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 140, 140, 40));

        jTextFieldCodProc.setFont(new java.awt.Font("Rubik", 0, 16)); // NOI18N
        jTextFieldCodProc.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(179, 179, 179)));
        jpanelProductos.add(jTextFieldCodProc, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 220, 100, 40));

        jLabel4.setFont(new java.awt.Font("Rubik Medium", 0, 14)); // NOI18N
        jLabel4.setText("Codigo Producto");
        jpanelProductos.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 200, 180, -1));

        jLabel5.setFont(new java.awt.Font("Rubik Medium", 0, 14)); // NOI18N
        jLabel5.setText("Nombre Producto");
        jpanelProductos.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 200, -1, -1));

        jLabel6.setFont(new java.awt.Font("Rubik Medium", 0, 14)); // NOI18N
        jLabel6.setText("Prec. Unit.");
        jpanelProductos.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 200, -1, -1));

        jTextFieldPrecioUnitario.setBackground(new java.awt.Color(233, 233, 233));
        jTextFieldPrecioUnitario.setFont(new java.awt.Font("Rubik", 1, 16)); // NOI18N
        jTextFieldPrecioUnitario.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(179, 179, 179)));
        jpanelProductos.add(jTextFieldPrecioUnitario, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 220, 80, 40));

        jLabel7.setFont(new java.awt.Font("Rubik Medium", 0, 14)); // NOI18N
        jLabel7.setText("Stock");
        jpanelProductos.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 200, -1, -1));

        jButtonAgregar.setBackground(new java.awt.Color(156, 234, 66));
        jButtonAgregar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/agregar-producto.png"))); // NOI18N
        jpanelProductos.add(jButtonAgregar, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 220, 130, 40));

        jLabel8.setFont(new java.awt.Font("Rubik Medium", 0, 14)); // NOI18N
        jLabel8.setText("Valor venta");
        jpanelProductos.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 450, -1, -1));

        jtxtValorVenta.setBackground(new java.awt.Color(233, 233, 233));
        jtxtValorVenta.setFont(new java.awt.Font("Rubik", 0, 16)); // NOI18N
        jtxtValorVenta.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(179, 179, 179)));
        jpanelProductos.add(jtxtValorVenta, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 470, 80, 40));

        jtxtDescuento.setBackground(new java.awt.Color(255, 250, 188));
        jtxtDescuento.setFont(new java.awt.Font("Rubik", 0, 16)); // NOI18N
        jtxtDescuento.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(179, 179, 179)));
        jpanelProductos.add(jtxtDescuento, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 470, 80, 40));

        jLabel9.setFont(new java.awt.Font("Rubik Medium", 0, 14)); // NOI18N
        jLabel9.setText("Descuento");
        jpanelProductos.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 450, -1, -1));

        jLabel10.setFont(new java.awt.Font("Rubik Medium", 0, 14)); // NOI18N
        jLabel10.setText("Subtotal");
        jpanelProductos.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 450, -1, -1));

        jtxtSubtotal.setFont(new java.awt.Font("Rubik", 0, 16)); // NOI18N
        jtxtSubtotal.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(179, 179, 179)));
        jpanelProductos.add(jtxtSubtotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 470, 80, 40));

        jtxtIGV.setBackground(new java.awt.Color(233, 233, 233));
        jtxtIGV.setFont(new java.awt.Font("Rubik", 0, 16)); // NOI18N
        jtxtIGV.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(179, 179, 179)));
        jpanelProductos.add(jtxtIGV, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 470, 80, 40));

        jLabel11.setFont(new java.awt.Font("Rubik Medium", 0, 14)); // NOI18N
        jLabel11.setText("IGV");
        jpanelProductos.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 450, -1, -1));

        jtxtTotalPagar.setBackground(new java.awt.Color(204, 255, 212));
        jtxtTotalPagar.setFont(new java.awt.Font("Rubik", 0, 16)); // NOI18N
        jtxtTotalPagar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(179, 179, 179)));
        jpanelProductos.add(jtxtTotalPagar, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 470, 214, 40));

        jLabel12.setFont(new java.awt.Font("Rubik Medium", 0, 14)); // NOI18N
        jLabel12.setText("Total a pagar");
        jpanelProductos.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 450, -1, -1));

        jButtonImprimir.setBackground(new java.awt.Color(238, 238, 238));
        jButtonImprimir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/imprimir-recibo.png"))); // NOI18N
        jpanelProductos.add(jButtonImprimir, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 170, 200, 120));

        jButtonGenerarVenta.setBackground(new java.awt.Color(238, 238, 238));
        jButtonGenerarVenta.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/generar-venta.png"))); // NOI18N
        jpanelProductos.add(jButtonGenerarVenta, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 30, 200, 120));

        jspnCantidadProducto.setFont(new java.awt.Font("Rubik", 0, 16)); // NOI18N
        jspnCantidadProducto.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(179, 179, 179)));
        jpanelProductos.add(jspnCantidadProducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 220, 80, 40));

        jTextFieldStock.setFont(new java.awt.Font("Rubik", 0, 16)); // NOI18N
        jpanelProductos.add(jTextFieldStock, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 220, 60, 40));

        jTableVenta.setFont(new java.awt.Font("Rubik", 0, 16)); // NOI18N
        jTableVenta.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jTableVenta);

        jpanelProductos.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 270, 770, 170));

        btnReporteVentas.setBackground(new java.awt.Color(238, 238, 238));
        btnReporteVentas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/boton-reportes.png"))); // NOI18N
        btnReporteVentas.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        btnReporteVentas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReporteVentasActionPerformed(evt);
            }
        });
        jpanelProductos.add(btnReporteVentas, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 300, 200, 150));

        jButtonCancelarVenta.setBackground(new java.awt.Color(204, 204, 204));
        jButtonCancelarVenta.setFont(new java.awt.Font("Rubik Medium", 1, 14)); // NOI18N
        jButtonCancelarVenta.setText("Cancelar");
        jpanelProductos.add(jButtonCancelarVenta, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 470, 150, 40));

        jButtonBuscarProd.setBackground(new java.awt.Color(153, 255, 255));
        jButtonBuscarProd.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/buscar-reporte.png"))); // NOI18N
        jpanelProductos.add(jButtonBuscarProd, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 220, 110, 40));

        jButtonBuscarCliente.setBackground(new java.awt.Color(255, 255, 255));
        jButtonBuscarCliente.setForeground(new java.awt.Color(255, 255, 255));
        jButtonBuscarCliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/buscar-reporte.png"))); // NOI18N
        jpanelProductos.add(jButtonBuscarCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 140, 110, 40));

        jtxtNombre.setFont(new java.awt.Font("Rubik", 0, 16)); // NOI18N
        jtxtNombre.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(179, 179, 179)));
        jpanelProductos.add(jtxtNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 220, 150, 40));

        jLabel13.setFont(new java.awt.Font("Rubik Medium", 0, 14)); // NOI18N
        jLabel13.setText("Cantidad");
        jpanelProductos.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 200, -1, -1));

        getContentPane().add(jpanelProductos, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 30, 1100, 540));

        FondoMenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/fondo-menu.jpg"))); // NOI18N
        getContentPane().add(FondoMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonRegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRegresarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonRegresarActionPerformed

    private void btnReporteVentasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReporteVentasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnReporteVentasActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormVentas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormVentas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormVentas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormVentas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormVentas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel FondoMenu;
    public javax.swing.JButton btnReporteVentas;
    public javax.swing.JButton jButtonAgregar;
    public javax.swing.JButton jButtonBuscarCliente;
    public javax.swing.JButton jButtonBuscarProd;
    public javax.swing.JButton jButtonCancelarVenta;
    public javax.swing.JButton jButtonGenerarVenta;
    public javax.swing.JButton jButtonImprimir;
    public javax.swing.JButton jButtonRegresar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane2;
    public javax.swing.JTable jTableVenta;
    public javax.swing.JTextField jTextFieldCodProc;
    public javax.swing.JTextField jTextFieldPrecioUnitario;
    public javax.swing.JTextField jTextFieldStock;
    public javax.swing.JComboBox<String> jcbxTipoDoc;
    private javax.swing.JPanel jpanelProductos;
    public javax.swing.JSpinner jspnCantidadProducto;
    public javax.swing.JTextField jtxtDescuento;
    public javax.swing.JTextField jtxtDniORuc;
    public javax.swing.JTextField jtxtIGV;
    public javax.swing.JTextField jtxtNomCliente;
    public javax.swing.JTextField jtxtNombre;
    public javax.swing.JTextField jtxtSubtotal;
    public javax.swing.JTextField jtxtTotalPagar;
    public javax.swing.JTextField jtxtValorVenta;
    private javax.swing.JLabel nameWelcome;
    private javax.swing.JLabel separadorMin;
    // End of variables declaration//GEN-END:variables
}
