/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vista;

import Modelo.Rol;

/**
 *
 * @author CRISTIAN
 */
public class FormEmpleados extends javax.swing.JFrame {

    /**
     * Creates new form FormEmpleados
     */
    public FormEmpleados() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jpanelAnadirEmpleado = new javax.swing.JPanel();
        nameWelcome = new javax.swing.JLabel();
        separadorMin = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jcbxCargo = new javax.swing.JComboBox<>();
        jbtnGuardarEmple = new javax.swing.JButton();
        jbtnActualizarEmple = new javax.swing.JButton();
        jbtnEliminarEmple = new javax.swing.JButton();
        jEbtnRegresar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableEmpleados = new javax.swing.JTable();
        jbtnConsultarEmple = new javax.swing.JButton();
        jtxtDni = new javax.swing.JTextField();
        jtxtNomEmple = new javax.swing.JTextField();
        jtxtTelefonoEmple = new javax.swing.JTextField();
        jbtnLimpiarCampos = new javax.swing.JButton();
        jtxtApellidosEmple = new javax.swing.JTextField();
        jPassword = new javax.swing.JPasswordField();
        FondoMenu = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1200, 600));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jpanelAnadirEmpleado.setBackground(new java.awt.Color(255, 255, 255));
        jpanelAnadirEmpleado.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        nameWelcome.setFont(new java.awt.Font("Rubik", 1, 28)); // NOI18N
        nameWelcome.setText("Empleados");
        jpanelAnadirEmpleado.add(nameWelcome, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 40, 390, 30));

        separadorMin.setFont(new java.awt.Font("Rubik", 1, 28)); // NOI18N
        separadorMin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/separador-min.png"))); // NOI18N
        jpanelAnadirEmpleado.add(separadorMin, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 80, -1, 10));

        jLabel1.setFont(new java.awt.Font("Rubik Medium", 0, 14)); // NOI18N
        jLabel1.setText("DNI");
        jpanelAnadirEmpleado.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 110, -1, -1));

        jLabel2.setFont(new java.awt.Font("Rubik Medium", 0, 14)); // NOI18N
        jLabel2.setText("Nombres");
        jpanelAnadirEmpleado.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 110, -1, -1));

        jLabel3.setFont(new java.awt.Font("Rubik Medium", 0, 14)); // NOI18N
        jLabel3.setText("Apellidos");
        jpanelAnadirEmpleado.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 190, -1, -1));

        jLabel4.setFont(new java.awt.Font("Rubik Medium", 0, 14)); // NOI18N
        jLabel4.setText("Teléfono");
        jpanelAnadirEmpleado.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 190, -1, -1));

        jLabel5.setFont(new java.awt.Font("Rubik Medium", 0, 14)); // NOI18N
        jLabel5.setText("Contraseña");
        jpanelAnadirEmpleado.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 270, -1, -1));

        jLabel6.setFont(new java.awt.Font("Rubik Medium", 0, 14)); // NOI18N
        jLabel6.setText("Cargo");
        jpanelAnadirEmpleado.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 270, -1, -1));

        jcbxCargo.setFont(new java.awt.Font("Rubik", 0, 16)); // NOI18N
        jpanelAnadirEmpleado.add(jcbxCargo, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 290, 210, 40));

        jbtnGuardarEmple.setBackground(new java.awt.Color(156, 234, 66));
        jbtnGuardarEmple.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/agregar-producto.png"))); // NOI18N
        jpanelAnadirEmpleado.add(jbtnGuardarEmple, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 360, 190, 60));

        jbtnActualizarEmple.setBackground(new java.awt.Color(142, 228, 255));
        jbtnActualizarEmple.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/btn-actualizar.png"))); // NOI18N
        jpanelAnadirEmpleado.add(jbtnActualizarEmple, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 450, 170, 60));

        jbtnEliminarEmple.setBackground(new java.awt.Color(255, 154, 165));
        jbtnEliminarEmple.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/eliminar.png"))); // NOI18N
        jpanelAnadirEmpleado.add(jbtnEliminarEmple, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 450, 180, 60));

        jEbtnRegresar.setBackground(new java.awt.Color(238, 238, 238));
        jEbtnRegresar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/btn-regresar.png"))); // NOI18N
        jpanelAnadirEmpleado.add(jEbtnRegresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(910, 450, 190, 60));

        jTableEmpleados.setFont(new java.awt.Font("Rubik", 0, 14)); // NOI18N
        jTableEmpleados.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTableEmpleados);

        jpanelAnadirEmpleado.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 90, 680, 350));

        jbtnConsultarEmple.setBackground(new java.awt.Color(190, 231, 244));
        jbtnConsultarEmple.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/buscar-reporte.png"))); // NOI18N
        jpanelAnadirEmpleado.add(jbtnConsultarEmple, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 30, 180, 50));

        jtxtDni.setFont(new java.awt.Font("Rubik", 0, 16)); // NOI18N
        jtxtDni.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        jpanelAnadirEmpleado.add(jtxtDni, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 130, 110, 40));

        jtxtNomEmple.setFont(new java.awt.Font("Rubik", 0, 16)); // NOI18N
        jtxtNomEmple.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        jpanelAnadirEmpleado.add(jtxtNomEmple, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 130, 250, 40));

        jtxtTelefonoEmple.setFont(new java.awt.Font("Rubik", 0, 16)); // NOI18N
        jtxtTelefonoEmple.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        jpanelAnadirEmpleado.add(jtxtTelefonoEmple, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 220, 160, 40));

        jbtnLimpiarCampos.setBackground(new java.awt.Color(204, 204, 204));
        jbtnLimpiarCampos.setFont(new java.awt.Font("Rubik Medium", 0, 14)); // NOI18N
        jbtnLimpiarCampos.setText("Limpiar campos");
        jpanelAnadirEmpleado.add(jbtnLimpiarCampos, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 470, 190, 40));

        jtxtApellidosEmple.setFont(new java.awt.Font("Rubik", 0, 16)); // NOI18N
        jtxtApellidosEmple.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        jpanelAnadirEmpleado.add(jtxtApellidosEmple, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 220, 160, 40));

        jPassword.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jPassword.setText("jPasswordField1");
        jPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jPasswordActionPerformed(evt);
            }
        });
        jpanelAnadirEmpleado.add(jPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 290, 140, 40));

        getContentPane().add(jpanelAnadirEmpleado, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, 1130, 540));

        FondoMenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/fondo-menu.jpg"))); // NOI18N
        getContentPane().add(FondoMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPasswordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jPasswordActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormEmpleados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormEmpleados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormEmpleados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormEmpleados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormEmpleados().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel FondoMenu;
    public javax.swing.JButton jEbtnRegresar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    public javax.swing.JPasswordField jPassword;
    private javax.swing.JScrollPane jScrollPane1;
    public javax.swing.JTable jTableEmpleados;
    public javax.swing.JButton jbtnActualizarEmple;
    public javax.swing.JButton jbtnConsultarEmple;
    public javax.swing.JButton jbtnEliminarEmple;
    public javax.swing.JButton jbtnGuardarEmple;
    public javax.swing.JButton jbtnLimpiarCampos;
    public javax.swing.JComboBox<Rol> jcbxCargo;
    private javax.swing.JPanel jpanelAnadirEmpleado;
    public javax.swing.JTextField jtxtApellidosEmple;
    public javax.swing.JTextField jtxtDni;
    public javax.swing.JTextField jtxtNomEmple;
    public javax.swing.JTextField jtxtTelefonoEmple;
    private javax.swing.JLabel nameWelcome;
    private javax.swing.JLabel separadorMin;
    // End of variables declaration//GEN-END:variables
}
