/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vista;

/**
 *
 * @author CRISTIAN
 */
public class FormCategorias extends javax.swing.JFrame {

    /**
     * Creates new form FormCategorias
     */
    public FormCategorias() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jpanelAnadirCargo = new javax.swing.JPanel();
        nameWelcome = new javax.swing.JLabel();
        separadorMin = new javax.swing.JLabel();
        jbtnGuardarCategoria = new javax.swing.JButton();
        jRregresar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableCategorias = new javax.swing.JTable();
        jbtnActualizarCategoria = new javax.swing.JButton();
        jbtnEliminarCategoria = new javax.swing.JButton();
        jtxtBusquedaCat = new javax.swing.JTextField();
        jtxtDescCategoria = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jbtnConsultarCategoria = new javax.swing.JButton();
        jtxtIdCat = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jtxtNombreCat = new javax.swing.JTextField();
        jbtnLimpiarCampos = new javax.swing.JButton();
        Fondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jpanelAnadirCargo.setBackground(new java.awt.Color(255, 255, 255));
        jpanelAnadirCargo.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        nameWelcome.setFont(new java.awt.Font("Rubik", 1, 28)); // NOI18N
        nameWelcome.setText("Categorías");
        jpanelAnadirCargo.add(nameWelcome, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 40, 160, 30));

        separadorMin.setFont(new java.awt.Font("Rubik", 1, 28)); // NOI18N
        separadorMin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/separador-min.png"))); // NOI18N
        jpanelAnadirCargo.add(separadorMin, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 80, -1, 10));

        jbtnGuardarCategoria.setBackground(new java.awt.Color(156, 234, 66));
        jbtnGuardarCategoria.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/agregar-producto.png"))); // NOI18N
        jpanelAnadirCargo.add(jbtnGuardarCategoria, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 390, 190, 60));

        jRregresar.setBackground(new java.awt.Color(238, 238, 238));
        jRregresar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/btn-regresar.png"))); // NOI18N
        jpanelAnadirCargo.add(jRregresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 460, 190, 60));

        jTableCategorias.setFont(new java.awt.Font("Rubik", 0, 14)); // NOI18N
        jTableCategorias.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTableCategorias);

        jpanelAnadirCargo.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 100, 630, 350));

        jbtnActualizarCategoria.setBackground(new java.awt.Color(142, 228, 255));
        jbtnActualizarCategoria.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/btn-actualizar.png"))); // NOI18N
        jpanelAnadirCargo.add(jbtnActualizarCategoria, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 460, 170, 60));

        jbtnEliminarCategoria.setBackground(new java.awt.Color(255, 154, 165));
        jbtnEliminarCategoria.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/eliminar.png"))); // NOI18N
        jpanelAnadirCargo.add(jbtnEliminarCategoria, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 460, 180, 60));

        jtxtBusquedaCat.setFont(new java.awt.Font("Rubik", 0, 16)); // NOI18N
        jtxtBusquedaCat.setForeground(new java.awt.Color(102, 102, 102));
        jtxtBusquedaCat.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        jtxtBusquedaCat.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jtxtBusquedaCatKeyReleased(evt);
            }
        });
        jpanelAnadirCargo.add(jtxtBusquedaCat, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 30, 220, 50));

        jtxtDescCategoria.setFont(new java.awt.Font("Rubik", 0, 16)); // NOI18N
        jtxtDescCategoria.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        jpanelAnadirCargo.add(jtxtDescCategoria, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 300, 220, 70));

        jLabel4.setFont(new java.awt.Font("Rubik Medium", 0, 14)); // NOI18N
        jLabel4.setText("Descripción");
        jpanelAnadirCargo.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 280, -1, -1));

        jbtnConsultarCategoria.setBackground(new java.awt.Color(190, 231, 244));
        jbtnConsultarCategoria.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/buscar-reporte.png"))); // NOI18N
        jpanelAnadirCargo.add(jbtnConsultarCategoria, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 30, 180, 50));

        jtxtIdCat.setBackground(new java.awt.Color(204, 204, 204));
        jtxtIdCat.setFont(new java.awt.Font("Rubik", 0, 16)); // NOI18N
        jtxtIdCat.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 102)));
        jpanelAnadirCargo.add(jtxtIdCat, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 130, 80, 40));

        jLabel5.setFont(new java.awt.Font("Rubik Medium", 0, 14)); // NOI18N
        jLabel5.setText("ID");
        jpanelAnadirCargo.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 110, -1, -1));

        jLabel6.setFont(new java.awt.Font("Rubik Medium", 0, 14)); // NOI18N
        jLabel6.setText("Nombre de categoría");
        jpanelAnadirCargo.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 190, -1, -1));

        jtxtNombreCat.setFont(new java.awt.Font("Rubik", 0, 16)); // NOI18N
        jtxtNombreCat.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        jpanelAnadirCargo.add(jtxtNombreCat, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 210, 220, 40));

        jbtnLimpiarCampos.setBackground(new java.awt.Color(204, 204, 204));
        jbtnLimpiarCampos.setFont(new java.awt.Font("Rubik Medium", 0, 14)); // NOI18N
        jbtnLimpiarCampos.setText("Limpiar campos");
        jpanelAnadirCargo.add(jbtnLimpiarCampos, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 470, 190, 40));

        getContentPane().add(jpanelAnadirCargo, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 30, 960, 540));

        Fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/fondo-menu.jpg"))); // NOI18N
        Fondo.setText("jLabel1");
        Fondo.setPreferredSize(new java.awt.Dimension(1200, 600));
        getContentPane().add(Fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1200, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jtxtBusquedaCatKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtxtBusquedaCatKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtBusquedaCatKeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormCategorias.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormCategorias.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormCategorias.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormCategorias.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormCategorias().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Fondo;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    public javax.swing.JButton jRregresar;
    private javax.swing.JScrollPane jScrollPane1;
    public javax.swing.JTable jTableCategorias;
    public javax.swing.JButton jbtnActualizarCategoria;
    public javax.swing.JButton jbtnConsultarCategoria;
    public javax.swing.JButton jbtnEliminarCategoria;
    public javax.swing.JButton jbtnGuardarCategoria;
    public javax.swing.JButton jbtnLimpiarCampos;
    private javax.swing.JPanel jpanelAnadirCargo;
    public javax.swing.JTextField jtxtBusquedaCat;
    public javax.swing.JTextField jtxtDescCategoria;
    public javax.swing.JTextField jtxtIdCat;
    public javax.swing.JTextField jtxtNombreCat;
    private javax.swing.JLabel nameWelcome;
    private javax.swing.JLabel separadorMin;
    // End of variables declaration//GEN-END:variables
}
