/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vista;

/**
 *
 * @author CRISTIAN
 */
public class FormRoles extends javax.swing.JFrame {

    /**
     * Creates new form FormRoles
     */
    public FormRoles() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jpanelAnadirCargo = new javax.swing.JPanel();
        nameWelcome = new javax.swing.JLabel();
        separadorMin = new javax.swing.JLabel();
        jbtnGuardarRol = new javax.swing.JButton();
        jRregresar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableRoles = new javax.swing.JTable();
        jbtnActualizarRol = new javax.swing.JButton();
        jbtnEliminarRol = new javax.swing.JButton();
        jtxtBusquedaRoles = new javax.swing.JTextField();
        jtxtNombreRol = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jbtnConsultarRol = new javax.swing.JButton();
        jtxtIdRol = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jbtnLimpiarCampos = new javax.swing.JButton();
        Fondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jpanelAnadirCargo.setBackground(new java.awt.Color(255, 255, 255));
        jpanelAnadirCargo.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        nameWelcome.setFont(new java.awt.Font("Rubik", 1, 28)); // NOI18N
        nameWelcome.setText("Roles");
        jpanelAnadirCargo.add(nameWelcome, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 40, 90, 30));

        separadorMin.setFont(new java.awt.Font("Rubik", 1, 28)); // NOI18N
        separadorMin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/separador-min.png"))); // NOI18N
        jpanelAnadirCargo.add(separadorMin, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 80, -1, 10));

        jbtnGuardarRol.setBackground(new java.awt.Color(156, 234, 66));
        jbtnGuardarRol.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/agregar-producto.png"))); // NOI18N
        jpanelAnadirCargo.add(jbtnGuardarRol, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 300, 190, 60));

        jRregresar.setBackground(new java.awt.Color(238, 238, 238));
        jRregresar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/btn-regresar.png"))); // NOI18N
        jpanelAnadirCargo.add(jRregresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 460, 190, 60));

        jTableRoles.setFont(new java.awt.Font("Rubik", 0, 14)); // NOI18N
        jTableRoles.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTableRoles);

        jpanelAnadirCargo.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 100, 630, 350));

        jbtnActualizarRol.setBackground(new java.awt.Color(142, 228, 255));
        jbtnActualizarRol.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/btn-actualizar.png"))); // NOI18N
        jpanelAnadirCargo.add(jbtnActualizarRol, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 460, 170, 60));

        jbtnEliminarRol.setBackground(new java.awt.Color(255, 154, 165));
        jbtnEliminarRol.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/eliminar.png"))); // NOI18N
        jpanelAnadirCargo.add(jbtnEliminarRol, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 460, 180, 60));

        jtxtBusquedaRoles.setFont(new java.awt.Font("Rubik", 0, 16)); // NOI18N
        jtxtBusquedaRoles.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        jtxtBusquedaRoles.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jtxtBusquedaRolesKeyReleased(evt);
            }
        });
        jpanelAnadirCargo.add(jtxtBusquedaRoles, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 30, 220, 50));

        jtxtNombreRol.setFont(new java.awt.Font("Rubik", 0, 16)); // NOI18N
        jtxtNombreRol.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        jpanelAnadirCargo.add(jtxtNombreRol, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 210, 220, 40));

        jLabel4.setFont(new java.awt.Font("Rubik Medium", 0, 14)); // NOI18N
        jLabel4.setText("Nombre de rol");
        jpanelAnadirCargo.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 190, -1, -1));

        jbtnConsultarRol.setBackground(new java.awt.Color(190, 231, 244));
        jbtnConsultarRol.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/buscar-reporte.png"))); // NOI18N
        jpanelAnadirCargo.add(jbtnConsultarRol, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 30, 180, 50));

        jtxtIdRol.setBackground(new java.awt.Color(204, 204, 204));
        jtxtIdRol.setFont(new java.awt.Font("Rubik", 0, 16)); // NOI18N
        jtxtIdRol.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(102, 102, 102), 1, true));
        jpanelAnadirCargo.add(jtxtIdRol, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 130, 80, 40));

        jLabel5.setFont(new java.awt.Font("Rubik Medium", 0, 14)); // NOI18N
        jLabel5.setText("ID");
        jpanelAnadirCargo.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 110, -1, -1));

        jbtnLimpiarCampos.setBackground(new java.awt.Color(204, 204, 204));
        jbtnLimpiarCampos.setFont(new java.awt.Font("Rubik Medium", 0, 14)); // NOI18N
        jbtnLimpiarCampos.setText("Limpiar campos");
        jpanelAnadirCargo.add(jbtnLimpiarCampos, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 470, 190, 40));

        getContentPane().add(jpanelAnadirCargo, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 30, 960, 540));

        Fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/fondo-menu.jpg"))); // NOI18N
        Fondo.setText("jLabel1");
        Fondo.setPreferredSize(new java.awt.Dimension(1200, 600));
        getContentPane().add(Fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1200, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jtxtBusquedaRolesKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtxtBusquedaRolesKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtBusquedaRolesKeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormRoles.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormRoles.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormRoles.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormRoles.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormRoles().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Fondo;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    public javax.swing.JButton jRregresar;
    private javax.swing.JScrollPane jScrollPane1;
    public javax.swing.JTable jTableRoles;
    public javax.swing.JButton jbtnActualizarRol;
    public javax.swing.JButton jbtnConsultarRol;
    public javax.swing.JButton jbtnEliminarRol;
    public javax.swing.JButton jbtnGuardarRol;
    public javax.swing.JButton jbtnLimpiarCampos;
    private javax.swing.JPanel jpanelAnadirCargo;
    public javax.swing.JTextField jtxtBusquedaRoles;
    public javax.swing.JTextField jtxtIdRol;
    public javax.swing.JTextField jtxtNombreRol;
    private javax.swing.JLabel nameWelcome;
    private javax.swing.JLabel separadorMin;
    // End of variables declaration//GEN-END:variables
}
