/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vista;

/**
 *
 * @author CRISTIAN
 */
public class FormMenu extends javax.swing.JFrame {

    /**
     * Creates new form FormMenu
     */
    public FormMenu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        btnVentasForm = new javax.swing.JButton();
        btnProductosForm = new javax.swing.JButton();
        btnCategoriasForm = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        btnInventarioForm = new javax.swing.JButton();
        btnRolesForm = new javax.swing.JButton();
        btnEmpleadosForm = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        nameWelcome = new javax.swing.JLabel();
        separadorMin = new javax.swing.JLabel();
        btnCerrarSesion = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        FondoMenu = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnVentasForm.setBackground(new java.awt.Color(238, 238, 238));
        btnVentasForm.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/boton-ventas.png"))); // NOI18N
        btnVentasForm.setBorder(null);
        btnVentasForm.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPanel2.add(btnVentasForm, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 198, 150));

        btnProductosForm.setBackground(new java.awt.Color(238, 238, 238));
        btnProductosForm.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/boton-productos.png"))); // NOI18N
        btnProductosForm.setBorder(null);
        jPanel2.add(btnProductosForm, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 170, -1, 150));

        btnCategoriasForm.setBackground(new java.awt.Color(238, 238, 238));
        btnCategoriasForm.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/btn-form-categorias.png"))); // NOI18N
        btnCategoriasForm.setBorder(null);
        btnCategoriasForm.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPanel2.add(btnCategoriasForm, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 330, -1, 150));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 40, 230, 510));

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnInventarioForm.setBackground(new java.awt.Color(238, 238, 238));
        btnInventarioForm.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/btn-inventario.png"))); // NOI18N
        btnInventarioForm.setBorder(null);
        btnInventarioForm.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPanel3.add(btnInventarioForm, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, -1, 150));

        btnRolesForm.setBackground(new java.awt.Color(238, 238, 238));
        btnRolesForm.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/btn-form-roles.png"))); // NOI18N
        btnRolesForm.setBorder(null);
        btnRolesForm.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPanel3.add(btnRolesForm, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 170, -1, 150));

        btnEmpleadosForm.setBackground(new java.awt.Color(238, 238, 238));
        btnEmpleadosForm.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/boton-empleados.png"))); // NOI18N
        btnEmpleadosForm.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 0, true));
        jPanel3.add(btnEmpleadosForm, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 330, -1, 150));

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(940, 40, 230, 510));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        nameWelcome.setFont(new java.awt.Font("Rubik", 1, 28)); // NOI18N
        nameWelcome.setText("Sistema de Gestión Pesquera");
        jPanel1.add(nameWelcome, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 10, 420, 30));

        separadorMin.setFont(new java.awt.Font("Rubik", 1, 28)); // NOI18N
        separadorMin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/separador-min.png"))); // NOI18N
        jPanel1.add(separadorMin, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 40, -1, 10));

        btnCerrarSesion.setBackground(new java.awt.Color(238, 238, 238));
        btnCerrarSesion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/cerrar-sesion 1.png"))); // NOI18N
        btnCerrarSesion.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 0, true));
        jPanel1.add(btnCerrarSesion, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 480, 204, 56));

        jPanel4.setLayout(new java.awt.BorderLayout());
        jPanel1.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 110, 270, 270));

        jPanel5.setLayout(new java.awt.BorderLayout());
        jPanel1.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 110, 270, 270));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 20, 940, 550));

        FondoMenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/fondo-menu.jpg"))); // NOI18N
        getContentPane().add(FondoMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormMenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel FondoMenu;
    public javax.swing.JButton btnCategoriasForm;
    public javax.swing.JButton btnCerrarSesion;
    public javax.swing.JButton btnEmpleadosForm;
    public javax.swing.JButton btnInventarioForm;
    public javax.swing.JButton btnProductosForm;
    public javax.swing.JButton btnRolesForm;
    public javax.swing.JButton btnVentasForm;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    public javax.swing.JPanel jPanel4;
    public javax.swing.JPanel jPanel5;
    private javax.swing.JLabel nameWelcome;
    private javax.swing.JLabel separadorMin;
    // End of variables declaration//GEN-END:variables
}
