/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vista;

/**
 *
 * @author CRISTIAN
 */
public class FormInventario extends javax.swing.JFrame {

    /**
     * Creates new form FormInventario
     */
    public FormInventario() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        nameWelcome = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableInventarioProductos = new javax.swing.JTable();
        jspnStockProInventario = new javax.swing.JSpinner();
        jLabel7 = new javax.swing.JLabel();
        jbtnConsultarInventario = new javax.swing.JButton();
        jIRegresar = new javax.swing.JButton();
        jbtnActualizarInventario = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jtxtCodProdInv = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jtxtNombreProdInv = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jcbxCategoriaInv = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        jtxtDescripcionProdInv = new javax.swing.JTextField();
        jbtnLimpiarCampos = new javax.swing.JButton();
        Fondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        nameWelcome.setFont(new java.awt.Font("Rubik", 1, 28)); // NOI18N
        nameWelcome.setText("Inventario");
        jPanel2.add(nameWelcome, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, 160, 30));

        jLabel4.setFont(new java.awt.Font("Rubik Medium", 0, 14)); // NOI18N
        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/separador-min.png"))); // NOI18N
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 50, -1, 20));

        jTableInventarioProductos.setFont(new java.awt.Font("Rubik", 0, 14)); // NOI18N
        jTableInventarioProductos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTableInventarioProductos);

        jPanel2.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 80, 560, 380));

        jspnStockProInventario.setFont(new java.awt.Font("Rubik", 0, 16)); // NOI18N
        jspnStockProInventario.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        jPanel2.add(jspnStockProInventario, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 310, 90, 40));

        jLabel7.setFont(new java.awt.Font("Rubik Medium", 0, 14)); // NOI18N
        jLabel7.setText("Stock");
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 290, -1, -1));

        jbtnConsultarInventario.setBackground(new java.awt.Color(190, 231, 244));
        jbtnConsultarInventario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/buscar-reporte.png"))); // NOI18N
        jPanel2.add(jbtnConsultarInventario, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 20, 180, 50));

        jIRegresar.setBackground(new java.awt.Color(238, 238, 238));
        jIRegresar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/btn-regresar.png"))); // NOI18N
        jPanel2.add(jIRegresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 470, 180, 50));

        jbtnActualizarInventario.setBackground(new java.awt.Color(142, 228, 255));
        jbtnActualizarInventario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/btn-actualizar.png"))); // NOI18N
        jPanel2.add(jbtnActualizarInventario, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 410, 170, 50));

        jLabel9.setFont(new java.awt.Font("Rubik Medium", 0, 14)); // NOI18N
        jLabel9.setText("Código");
        jPanel2.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 90, -1, -1));

        jtxtCodProdInv.setFont(new java.awt.Font("Rubik", 0, 16)); // NOI18N
        jtxtCodProdInv.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        jtxtCodProdInv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtCodProdInvActionPerformed(evt);
            }
        });
        jPanel2.add(jtxtCodProdInv, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 110, 150, 40));

        jLabel2.setFont(new java.awt.Font("Rubik Medium", 0, 14)); // NOI18N
        jLabel2.setText("Nombre");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 90, -1, -1));

        jtxtNombreProdInv.setFont(new java.awt.Font("Rubik", 0, 16)); // NOI18N
        jtxtNombreProdInv.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        jPanel2.add(jtxtNombreProdInv, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 110, 180, 40));

        jLabel8.setFont(new java.awt.Font("Rubik Medium", 0, 14)); // NOI18N
        jLabel8.setText("Categoría");
        jPanel2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 290, -1, -1));

        jcbxCategoriaInv.setFont(new java.awt.Font("Rubik", 0, 16)); // NOI18N
        jcbxCategoriaInv.setForeground(new java.awt.Color(51, 51, 51));
        jPanel2.add(jcbxCategoriaInv, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 310, 150, 40));

        jLabel5.setFont(new java.awt.Font("Rubik Medium", 0, 14)); // NOI18N
        jLabel5.setText("Descripción");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 160, -1, -1));

        jtxtDescripcionProdInv.setFont(new java.awt.Font("Rubik", 0, 16)); // NOI18N
        jtxtDescripcionProdInv.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        jPanel2.add(jtxtDescripcionProdInv, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 180, 340, 100));

        jbtnLimpiarCampos.setBackground(new java.awt.Color(204, 204, 204));
        jbtnLimpiarCampos.setFont(new java.awt.Font("Rubik Medium", 0, 14)); // NOI18N
        jbtnLimpiarCampos.setForeground(new java.awt.Color(51, 51, 51));
        jbtnLimpiarCampos.setText("Limpiar campos");
        jPanel2.add(jbtnLimpiarCampos, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 470, 190, 40));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 30, 980, 540));

        Fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/fondo-menu.jpg"))); // NOI18N
        Fondo.setText("jLabel1");
        Fondo.setPreferredSize(new java.awt.Dimension(1200, 600));
        getContentPane().add(Fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1200, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jtxtCodProdInvActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtCodProdInvActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtCodProdInvActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormInventario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormInventario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormInventario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormInventario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormInventario().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Fondo;
    public javax.swing.JButton jIRegresar;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    public javax.swing.JTable jTableInventarioProductos;
    public javax.swing.JButton jbtnActualizarInventario;
    public javax.swing.JButton jbtnConsultarInventario;
    public javax.swing.JButton jbtnLimpiarCampos;
    public javax.swing.JComboBox<String> jcbxCategoriaInv;
    public javax.swing.JSpinner jspnStockProInventario;
    public javax.swing.JTextField jtxtCodProdInv;
    public javax.swing.JTextField jtxtDescripcionProdInv;
    public javax.swing.JTextField jtxtNombreProdInv;
    private javax.swing.JLabel nameWelcome;
    // End of variables declaration//GEN-END:variables
}
